breeding:
  checks:
  - radius: 6
    limit: 100
  warnRadius: 32
  warnTimer: 30
natural:
  tpsThreshold: 17.0
  lowTpsSpawnChance: 0.01
  worlds:
  - name: default
    enabled: false
  - name: my_world
    enabled: true
    chunkRadius: 4
    mobLimit: 24
