main: com.cavetale.cullmob.CullMobPlugin
name: CullMob
version: 0.1
api-version: '1.21.8'
description: Reduce large clusters of mobs
author: StarTux
website: https://cavetale.com
depend: []
softdepend: []
commands:
  cullmob:
    description: CullMob Command
    permission: cullmob.cullmob
    usage: |-
      /cullmob reload - Reload config
      /cullmob list - List recent actions
      /cullmob info - Show config info
      /cullmob save - Save default config
permissions:
  cullmob.cullmob:
    description: Use /cullmob
